spring:
  datasource:
#    url: jdbc:postgresql://localhost:5432/notification-db?stringtype=unspecified&reWriteBatchedInserts=true
#    username: notification
#    password: notification

  data:
    redis:
      port: 6379
      host: localhost
      password: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81