version: '3.9'

services:
  shopping-management-svc:
    container_name: shopping-management-svc
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8050:8050"
    environment:
      - ENV_PROFILE=docker
    networks:
      - infrastructure_e-commerce-network
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M

networks:
  infrastructure_e-commerce-network:
    external: true
    driver: bridge