spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payments-db?stringtype=unspecified&reWriteBatchedInserts=true
    username: payments
    password: payments

  data:
    redis:
      port: 6379
      host: localhost
      password: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81