version: "3.9"

services:
  nginx:
    image: nginx:stable-alpine3.17-slim
    container_name: nginx
    restart: always
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "4000:4000"
    networks:
      - infrastructure_e-commerce-network
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M

networks:
  infrastructure_e-commerce-network:
    external: true
    driver: bridge
