spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/orders-db?stringtype=unspecified&reWriteBatchedInserts=true
    username: orders
    password: orders

  data:
    redis:
      port: 6379
      host: localhost
      password: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81