spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/orders-db?stringtype=unspecified&reWriteBatchedInserts=true
    username: orders
    password: orders

  data:
    redis:
      port: 6379
      host: localhost
      password: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    mongodb:
      uri: mongodb://${MONGO_USER:appusr}:${MONGO_PASSWORD:appdev}@${MONGO_HOST:localhost}:${MONGO_PORT:27018}/orders-db