spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product-db?stringtype=unspecified&reWriteBatchedInserts=true
    username: product
    password: product

  data:
    redis:
      port: 6379
      host: localhost
      password: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81