version: '3.9'

services:

  mongo:
    image: mongo
    container_name: mongo-container
    restart: always
    networks:
      - e-commerce-network
    ports:
      - "27017:27017"
    volumes:
      - D:\docker-volumes\mongo\data\db:/data/db
#      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: appusr
      MONGO_INITDB_ROOT_PASSWORD: appdev

networks:
  e-commerce-network:
    driver: bridge