version: '3.9'

services:

  mongo:
    image: mongo
    container_name: mongo-container
    restart: always
    networks:
      - e-commerce-network
    ports:
      - "27017:27017"
    volumes:
      - D:\docker-volumes\mongo\data\db:/data/db
      - ./db-scripts/mongo/initdb.d:/docker-entrypoint-initdb.d/
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE=$MONGO_DB
      - MONGO_DB_USERNAME=$MONGO_DB_USERNAME
      - MONGO_DB_PASSWORD=$MONGO_DB_PASSWORD

networks:
  e-commerce-network:
    driver: bridge