version: '3.9'
services:

  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib:0.82.0
    restart: "unless-stopped"
    networks:
      - e-commerce-network
    command:
      - --config=/etc/otelcol-cont/otel-collector.yml
    volumes:
      - ./config/collector/otel-collector.yml:/etc/otelcol-cont/otel-collector.yml
    ports:
      - "1888:1888" # pprof extension
      - "8888:8888" # Prometheus metrics exposed by the collector
      - "8889:8889" # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP http receiver
      - "55679:55679" # zpages extension

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.47.2
    networks:
      - e-commerce-network
    restart: "unless-stopped"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  tempo:
    container_name: tempo
    restart: "unless-stopped"
    networks:
      - e-commerce-network
    image: grafana/tempo:2.2.4
    command: [ "-config.file=/etc/tempo.yml" ]
    volumes:
      - ./config/tempo/tempo.yml:/etc/tempo.yml
    ports:
      - "14268"  # jaeger ingest
      - "3200:3200"   # tempo
      - "4317"  # otlp grpc
      - "4318"  # otlp http
      - "9411"   # zipkin

  jaeger-server:
    image: jaegertracing/all-in-one:1.18.1
    container_name: jaeger-server
    restart: "unless-stopped"
    networks:
      - e-commerce-network
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"

  loki:
    container_name: loki
    restart: "unless-stopped"
    networks:
      - e-commerce-network
    image: grafana/loki:latest
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"

  grafana:
    container_name: grafana
    restart: "unless-stopped"
    networks:
      - e-commerce-network
    image: grafana/grafana:10.2.0
    ports:
      - "3000:3000"
    depends_on:
      - otel-collector
      - tempo
      - prometheus
      - jaeger-server

  elasticsearch:
    image: elasticsearch:8.13.0
    container_name: elasticsearch
    restart: "unless-stopped"
    networks:
      - e-commerce-network
    environment:
      - node.name=es-node
      - cluster.name=es-cluster
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: kibana:8.13.0
    container_name: kibana
    restart: "unless-stopped"
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"
    ports:
      - "5601:5601"
    networks:
      - e-commerce-network
    depends_on:
      - elasticsearch

networks:
  e-commerce-network:
    driver: bridge