server:
  port: ${SERVER_PORT:8040}

spring:
  profiles:
    active: ${ACTIVE_PROFILE:dev}
  application:
    name: edge-gateway-svc
  cloud:
    gateway:
      routes:
        - id: order-management-svc
          uri: http://localhost:8051
          predicates:
            - Path=/order-management-svc/**
          filters:
            - RewritePath=/order-management-svc/(?<path>.*), /$\{path}



logging.level:
  org.springframework.cloud.gateway: DEBUG
  org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
  org.springframework.web.server.adapter.HttpWebHandlerAdapter: TRACE