version: '3.9'

services:
  edge-gateway-svc:
    container_name: edge-gateway-svc
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8040:8040"
    environment:
      - ENV_PROFILE=docker
    networks:
      - infrastructure_e-commerce-network
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M
networks:
  infrastructure_e-commerce-network:
    external: true
    driver: bridge